name = "backoffice"
type = "javascript"

account_id = "49352e8d5379bd6e7b57ad393d3bc2b9"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-06"
kv_namespaces = [
  { binding = "HIGHLIGHTED", preview_id = "10cf29ecac6f4237960cbf667e8aab07", id = "ef2de6545c7d4d4eb86cf596fd6af99a" }
]

[site]
bucket = "./public"
entry-point = "dist"

[env.development]
name = "backoffice-development"

[build]
command = "yarn build"
[build.upload]
format = "service-worker"
